### ISSUE TITLE
dependencies?

### ISSUE THREAD

**Issue by bgrayburn** [cytoscape/cytoscape.js-cola#5]
is there a reason why the dependencies aren't included in the package? I'm getting a error saying `cola is not defined`

**Comment by clemsos** [comment]
Meteor package has no dependencies.

```
=> Started proxy.                             
=> Meteor 1.2.1 is available. Update this project with 'meteor update'.
=> Started MongoDB.                               
W20160116-14:42:30.161(1)? (STDERR) 
W20160116-14:42:30.161(1)? (STDERR) /home/clemsos/.meteor/packages/meteor-tool/.1.1.9.etaiou++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160116-14:42:30.161(1)? (STDERR) 						throw(ex);
W20160116-14:42:30.161(1)? (STDERR) 						      ^
W20160116-14:42:30.212(1)? (STDERR) ReferenceError: cola is not defined
W20160116-14:42:30.212(1)? (STDERR)     at Package (packages/maxkfranz_cytoscape-cola/packages/maxkfranz_cytoscape-cola.js:521:1)
W20160116-14:42:30.212(1)? (STDERR)     at Package (packages/maxkfranz_cytoscape-cola/packages/maxkfranz_cytoscape-cola.js:524:1)
W20160116-14:42:30.212(1)? (STDERR)     at Package (packages/maxkfranz_cytoscape-cola/packages/maxkfranz_cytoscape-cola.js:528:1)
W20160116-14:42:30.212(1)? (STDERR)     at /home/clemsos/Dev/topogram/topogram-client/.meteor/local/build/programs/server/packages/maxkfranz_cytoscape-cola.js:546:4
W20160116-14:42:30.212(1)? (STDERR)     at /home/clemsos/Dev/topogram/topogram-client/.meteor/local/build/programs/server/packages/maxkfranz_cytoscape-cola.js:553:3
W20160116-14:42:30.212(1)? (STDERR)     at /home/clemsos/Dev/topogram/topogram-client/.meteor/local/build/programs/server/boot.js:242:10
W20160116-14:42:30.212(1)? (STDERR)     at Array.forEach (native)
W20160116-14:42:30.212(1)? (STDERR)     at Function._.each._.forEach (/home/clemsos/.meteor/packages/meteor-tool/.1.1.9.etaiou++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160116-14:42:30.212(1)? (STDERR)     at /home/clemsos/Dev/topogram/topogram-client/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8
I20160116-14:42:35.783(1)? on the server      
```

**Comment by clemsos** [comment]
Tried to install the Meteor package for cola, no chances : https://atmospherejs.com/tdj/cola

**Comment by maxkfranz** [comment]
Download Cola.js (npm / ddl / etc) and follow the usage instructions: https://github.com/cytoscape/cytoscape.js-cola#usage-instructions

Cola is a separate, maintained library on npm etc.  There's no reason to include it here.
